# Generated by Django 4.2.6 on 2023-11-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('category', models.TextField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=255)),
                ('payment_mode', models.TextField(max_length=50)),
                ('bank', models.TextField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25)),
                ('complaint', models.TextField(max_length=255)),
            ],
        ),
    ]
